version: '2'

services:
  backend:
    image: 'hades-backend-image'
    build:
      context: ..
    container_name: hades
    ports:
      - '6358:8081'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hades
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hades-dev


  db:
    image: 'hades-db-image'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hades-dev