import {Component, Output} from '@angular/core';

@Component({
  selector: 'app-homeworks',
  templateUrl: './homeworks.component.html',
  styleUrls: ['./homeworks.component.scss']
})
export class HomeworksComponent {
  @Output()
  allHomeworksList: any =  [
    {
      name: "9. nädala kodutööd",
      text: `<p style='margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;margin-left:0cm;line-height:115%;font-size:35px;font-family:"Arial",sans-serif;'>9. n&auml;dala kodu&uuml;lesanded</p>
<h1 style='margin-top:20.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>&Uuml;lesanne 1. Retseptid</h1>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Miina tegi suures koguses maasikamoosi, kuid ikka on tal &uuml;le nii maasikaid kui ka suhkrut. Ta otsib v&auml;lja magustoitude retseptid ning lisab nende koostisosad faili nimega <strong>retseptid.txt</strong> nii, et igal real on vastava retsepti koostisosad komaga eraldatud.</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Kirjutada programm, mis</p>
<ol start="1" style="margin-bottom:0cm;margin-top:0cm;" type="1">
    <li style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>loeb funtksioonis failist_j&auml;rjendisse failist retseptid kahem&otilde;&otilde;tmelisse j&auml;rjendisse;</li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>v&auml;ljastab nende retseptide koostisosad, mis kasutavad nii <strong>suhkrut</strong> kui ka <strong>maasikaid</strong>.</li>
</ol>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>N&auml;ide programmi t&ouml;&ouml;st</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>N&auml;iteks retseptid.txt sisu on</p>
<table style="width: 4.5e+2pt;border-collapse:collapse;border:none;">
    <tbody>
        <tr>
            <td style="width: 451.45pt;border: 1pt solid black;padding: 5pt;vertical-align: top;">
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;'>muna,suhkur,jahu,kohupiim,vahukoor,maasikad</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;'>k&uuml;psised,v&otilde;i,toorjuust,hapukoor,jahu,suhkur,muna</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;'>banaanid,maasikad,apelsinimahl,suhkur,maitsestamata jogurt</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;'>v&otilde;i,suhkur,tume &scaron;okolaad,muna,jahu</p>
            </td>
        </tr>
    </tbody>
</table>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Programmi t&ouml;&ouml;:</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&gt;&gt;&gt; %Run 2.3a.py</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Retseptid, milleks on vaja maasikaid ja suhkrut:</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>[&apos;muna&apos;, &apos;suhkur&apos;, &apos;jahu&apos;, &apos;kohupiim&apos;, &apos;vahukoor&apos;, &apos;maasikad&apos;]</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>[&apos;banaanid&apos;, &apos;maasikad&apos;, &apos;apelsinimahl&apos;, &apos;suhkur&apos;, &apos;maitsestamata jogurt&apos;]</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
<h1 style='margin-top:20.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>&Uuml;lesanne 2. Bingo reeglite kontrollimine</h1>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Koostada programm, mis loeb failist kahem&otilde;&otilde;tmelisse j&auml;rjendisse bingonumbrid.</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>N&auml;ide failist bingo.txt:</p>
<table style="width: 4.5e+2pt;border-collapse:collapse;border:none;">
    <tbody>
        <tr>
            <td style="width: 451.45pt;border: 1pt solid black;padding: 5pt;vertical-align: top;">
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;border:none;'>1 30 34 55 75</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;border:none;'>10 16 40 50 67</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;border:none;'>5 20 38 48 61</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;border:none;'>4 26 43 49 70</p>
                <p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Arial",sans-serif;margin:0cm;border:none;'>15 17 33 51 66</p>
            </td>
        </tr>
    </tbody>
</table>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Koostada funktsioon failist_j&auml;rjendisse, mis saab argumendiks failinime ja tagastab kahem&otilde;&otilde;tmelise j&auml;rjendi bingov&auml;ljaku arvudega (t&auml;isarvu t&uuml;&uuml;pi).</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>N&auml;ide funktsiooni failist_j&auml;rjendisse t&ouml;&ouml;st eelneva n&auml;idisfailiga bingo.txt:</p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:13px;line-height:115%;">&gt;&gt;&gt; failist_j&auml;rjendisse(&quot;bingo.txt&quot;)</span></p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:13px;line-height:115%;">[[1, 30, 34, 55, 75], [10, 16, 40, 50, 67], [5, 20, 38, 48, 61], [4, 26, 43, 49, 70], [15, 17, 33, 51, 66]]</span></p>
<p style='margin-top:10.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Koostada funktsioon on_bingo_tabel, mis v&otilde;tab argumendiks 5 x 5 maatriksi, milles iga element on t&auml;isarv l&otilde;igust 1 - 75, ning tagastab t&otilde;ev&auml;&auml;rtuse vastavalt sellele, kas arvud selles tabelis on veergudesse jaotatud vastavalt Bingo Loto reeglitele.</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Et tegu oleks korrektse Bingo Loto m&auml;nguv&auml;ljaga, peavad vasakpoolseimas veerus olevad arvud kuuluma l&otilde;iku 1 - 15, j&auml;rgmises veerus olevad arvud l&otilde;iku 16 - 30 ja nii edasi, kuni viimases veerus on ainult arvud l&otilde;igust 61 - 75.</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Lihtsuse m&otilde;ttes v&otilde;ib siin &uuml;lesandes eeldada, et k&otilde;ik arvud on antud tabelis unikaalsed ehk &uuml;kski arv ei esine tabelis rohkem kui &uuml;ks kord. Huvi korral proovige kontrollida ka arvude unikaalsust, et ei peetaks korrektseks tabelit, mis on muidu reeglitele vastav, aga milles on kaks &uuml;hesugust arvu. Kui olete oma programmile lisanud unikaalsuse kontrolli, siis peab funktsiooni nimeks olema on_bingo_tabel_extra.</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>N&auml;ited funktsiooni eraldi rakendamisest</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&gt;&gt;&gt; on_bingo_tabel([[1, 30, 34, 55, 75],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;[10, 16, 40, 50, 67],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;[5, 20, 38, 48, 61],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;[4, 26, 43, 49, 70],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;[15, 17, 33, 51, 66]])</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>True</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&gt;&gt;&gt; on_bingo_tabel([[1, 30, 34, 55, 76],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;[10, 16, 40, 50, 67],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[5, 20, 38, 48, 61],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[4, 26, 43, 49, 70],</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[15, 17, 33, 51, 66]])</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>False</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Lahendamisel v&otilde;ite vajadusel inspiratsiooni ammutada abistavast<a href="http://www.uttv.ee/naita?id=25545"><span style="color:windowtext;text-decoration:none;">&nbsp;</span></a><a href="http://www.uttv.ee/naita?id=25545"><span style="color:#1155CC;">videost</span></a>.</p>
<p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Kui olete juba hulk aega proovinud &uuml;lesannet iseseisvalt lahendada ja see ikka ei &otilde;nnestu, siis v&otilde;ib-olla saate abi<a href="http://progtugi.cs.ut.ee/#/ts/58ee3ea52854d5eb164bb57f/"><span style="color:windowtext;text-decoration:none;">&nbsp;</span></a><a href="http://progtugi.cs.ut.ee/#/ts/58ee3ea52854d5eb164bb57f/"><span style="color:#1155CC;">murelahendajast</span></a>.</p>`
    },
    {
      name: "Ülesannete loomine",
      text: ` <style type="text/css">
      html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
      a.comment-indicator:hover + div.comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em }
      a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em }
      div.comment { display:none }
      table { border-collapse:collapse; page-break-after:always }
      .gridlines td { border:1px dotted black }
      .gridlines th { border:1px dotted black }
      .b { text-align:center }
      .e { text-align:center }
      .f { text-align:right }
      .inlineStr { text-align:left }
      .n { text-align:right }
      .s { text-align:left }
      td.style0 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10.0pt; background-color:white }
      th.style0 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10.0pt; background-color:white }
      td.style1 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      th.style1 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      td.style2 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      th.style2 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      td.style3 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      th.style3 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      td.style4 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; text-decoration:underline; color:#0000FF; font-family:'Calibri'; font-size:10pt; background-color:white }
      th.style4 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; text-decoration:underline; color:#0000FF; font-family:'Calibri'; font-size:10pt; background-color:white }
      td.style5 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; text-decoration:underline; color:#000000; font-family:'Calibri'; font-size:10pt; background-color:white }
      th.style5 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; text-decoration:underline; color:#000000; font-family:'Calibri'; font-size:10pt; background-color:white }
      td.style6 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      th.style6 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      td.style7 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      th.style7 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
      td.style8 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11.0pt; background-color:white }
      th.style8 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11.0pt; background-color:white }
      table.sheet0 col.col0 { width:62.35555484pt }
      table.sheet0 col.col1 { width:107.76666543pt }
      table.sheet0 col.col2 { width:58.28888822pt }
      table.sheet0 col.col3 { width:168.08888696pt }
      table.sheet0 col.col4 { width:50.83333275pt }
      table.sheet0 col.col5 { width:67.777777pt }
      table.sheet0 col.col6 { width:42pt }
      table.sheet0 col.col7 { width:42.69999951pt }
      table.sheet0 col.col8 { width:67.777777pt }
      table.sheet0 col.col9 { width:58.96666599pt }
      table.sheet0 col.col10 { width:42pt }
      table.sheet0 col.col11 { width:42pt }
      table.sheet0 col.col12 { width:42pt }
      table.sheet0 col.col13 { width:42pt }
      table.sheet0 col.col14 { width:42pt }
      table.sheet0 col.col15 { width:42pt }
      table.sheet0 col.col16 { width:42pt }
      table.sheet0 col.col17 { width:42pt }
      table.sheet0 col.col18 { width:42pt }
      table.sheet0 col.col19 { width:42pt }
      table.sheet0 col.col20 { width:42pt }
      table.sheet0 col.col21 { width:42pt }
      table.sheet0 col.col22 { width:42pt }
      table.sheet0 col.col23 { width:42pt }
      table.sheet0 col.col24 { width:42pt }
      table.sheet0 col.col25 { width:42pt }
      table.sheet0 col.col26 { width:42pt }
      table.sheet0 col.col27 { width:42pt }
      table.sheet0 col.col28 { width:42pt }
      table.sheet0 tr { height:15.75pt }
    </style>
  </head>

  <body>
<style>
@page { margin-left: 0.7in; margin-right: 0.7in; margin-top: 0.75in; margin-bottom: 0.75in; }
body { margin-left: 0.7in; margin-right: 0.7in; margin-top: 0.75in; margin-bottom: 0.75in; }
</style>
    <table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0 gridlines">
        <col class="col0">
        <col class="col1">
        <col class="col2">
        <col class="col3">
        <col class="col4">
        <col class="col5">
        <col class="col6">
        <col class="col7">
        <col class="col8">
        <col class="col9">
        <col class="col10">
        <col class="col11">
        <col class="col12">
        <col class="col13">
        <col class="col14">
        <col class="col15">
        <col class="col16">
        <col class="col17">
        <col class="col18">
        <col class="col19">
        <col class="col20">
        <col class="col21">
        <col class="col22">
        <col class="col23">
        <col class="col24">
        <col class="col25">
        <col class="col26">
        <col class="col27">
        <col class="col28">
        <tbody>
          <tr class="row0">
            <td class="column0 style1 s">Nädal</td>
            <td class="column1 style1 s">Teema</td>
            <td class="column2 style1 s">Tüüp</td>
            <td class="column3 style1 s">Vana ülesanne</td>
            <td class="column4 style1 s">Kas uuendame?</td>
            <td class="column5 style1 s">Uue ülesande nimi</td>
            <td class="column6 style1 s">Link</td>
            <td class="column7 style1 s">Tekst?</td>
            <td class="column8 style1 s">Automaatkontroll</td>
            <td class="column9 style1 s">Vestlusagent (murelahendaja)</td>
            <td class="column10 style1 s">Valmis?</td>
            <td class="column11 style1 s">Kommentaar</td>
            <td class="column12 style2 null"></td>
            <td class="column13 style2 null"></td>
            <td class="column14 style2 null"></td>
            <td class="column15 style2 null"></td>
            <td class="column16 style2 null"></td>
            <td class="column17 style2 null"></td>
            <td class="column18 style2 null"></td>
            <td class="column19 style2 null"></td>
            <td class="column20 style2 null"></td>
            <td class="column21 style2 null"></td>
            <td class="column22 style2 null"></td>
            <td class="column23 style2 null"></td>
            <td class="column24 style2 null"></td>
            <td class="column25 style2 null"></td>
            <td class="column26 style2 null"></td>
            <td class="column27 style2 null"></td>
            <td class="column28 style2 null"></td>
          </tr>
          <tr class="row1">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">1. Poiste ja tüdrukute arv</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row2">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">2. Taksohinnad</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row3">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">3. Sünnikuupäev isikukoodist </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row4">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">Vabatahtlik lisaülesanne. Värvid </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row5">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">1. Kuude nimed </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row6">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">2. Isikukoodi osad </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row7">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">3. Kirjete töötlemine </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row8">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">4. Sõne arvuks </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row9">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">5. Isikukoodi kontroll </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row10">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">6. Ridade ümberjärjestamine </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row11">
            <td class="column0 style3 s">7. nädal</td>
            <td class="column1 style3 s">Järjend</td>
            <td class="column2 style3 s">Lisaülesanne</td>
            <td class="column3 style3 s">3.  lisaülesanne - Veiderdav tekst</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row12">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">1. Bingo!</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6 style4 s"><a href="https://courses.cs.ut.ee/2022/programmeerimine/fall/Main/Kodu8" title="">https://courses.cs.ut.ee/2022/programmeerimine/fall/Main/Kodu8</a></td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row13">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">2. Filmide nimekiri</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6 style4 s"><a href="https://courses.cs.ut.ee/2022/programmeerimine/fall/Main/Kodu8" title="">https://courses.cs.ut.ee/2022/programmeerimine/fall/Main/Kodu8</a></td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row14">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">3. Juku filmiandmebaas</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6 style4 s"><a href="https://courses.cs.ut.ee/2022/programmeerimine/fall/Main/Kodu8" title="">https://courses.cs.ut.ee/2022/programmeerimine/fall/Main/Kodu8</a></td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row15">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">1. Absoluutväärtuste list</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row16">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">2. Lihtne krüptimine</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row17">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">3. Erinevad sõnad</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row18">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">4. Järjestuse kontroll</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row19">
            <td class="column0 style3 s">8. nädal</td>
            <td class="column1 style3 s">Järjend II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">5. Sõnastik koos autokorrektoriga</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row20">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">1. Andmete silumine</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5 style3 s">1. Retseptid </td>
            <td class="column6 style5 s"><a href="https://courses.cs.ut.ee/2022/programmeerimine/Main/Kodu9" title="">https://courses.cs.ut.ee/2022/programmeerimine/Main/Kodu9</a></td>
            <td class="column7 style3 s">Tauno</td>
            <td class="column8 style3 s">Reimo</td>
            <td class="column9 style3 s">Maike</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row21">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">2. minu_shuffle</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5 style3 s">2. Bingo reeglite kontrollimine</td>
            <td class="column6 style5 s"><a href="https://courses.cs.ut.ee/2022/programmeerimine/Main/Kodu9" title="">https://courses.cs.ut.ee/2022/programmeerimine/Main/Kodu9</a></td>
            <td class="column7 style3 s">Tauno</td>
            <td class="column8 style3 s">Reimo</td>
            <td class="column9 style3 s">Maike</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row22">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">1. Sõnapikkuste analüüs </td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row23">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">2. Listi elementide järjestamine </td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row24">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">3. Oma split</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row25">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">4. Kauplusejärjekord </td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row26">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">5. Järjestikused naturaalarvud </td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row27">
            <td class="column0 style3 s">9. nädal</td>
            <td class="column1 style3 s">Kahekordne tsükkel. Failitöötlus</td>
            <td class="column2 style3 s">Lisaülesanne</td>
            <td class="column3 style3 s">4. lisaülesanne - Sõnade arvamine</td>
            <td class="column4 style3 null"></td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row28">
            <td class="column0 style3 s">10. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">1. Teksti analüüs </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row29">
            <td class="column0 style3 s">10. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">2. Trips-traps-trull </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row30">
            <td class="column0 style3 s">10. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">0. Järjend hulgaks (soojendusülesanne) </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row31">
            <td class="column0 style3 s">10. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">1. Hulkade otsekorrutis </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row32">
            <td class="column0 style3 s">10. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">2. Sugupuu </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row33">
            <td class="column0 style3 s">10. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">3. Pikslimaatriks </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row34">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">1. Lapsed ja vanemad</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row35">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">2. Maatriksi transponeerimine kõrvaldiagonaali järgi</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5 style3 s">2. Noolemängu punktid</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row36">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">1. Valuutad </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row37">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">2. Kontaktid </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row38">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">3. Lennud (raskem ülesanne) </td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row39">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">-</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5 style3 s">2. Maatriksi transponeerimine kõrvaldiagonaali järgi</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row40">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Harjutus</td>
            <td class="column3 style3 s">-</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5 style3 null"></td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row41">
            <td class="column0 style3 s">11. nädal</td>
            <td class="column1 style3 s">Andmestruktuurid II</td>
            <td class="column2 style3 s">Lisaülesanne</td>
            <td class="column3 style3 s">5. lisaülesanne - Ristmik</td>
            <td class="column4 style3 s">Jah</td>
            <td class="column5 style3 s">??</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row42">
            <td class="column0 style3 s">15. nädal</td>
            <td class="column1 style3 s">OOP</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">1. Garaaž</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row43">
            <td class="column0 style3 s">15. nädal</td>
            <td class="column1 style3 s">OOP</td>
            <td class="column2 style3 s">Kodutöö</td>
            <td class="column3 style3 s">2. Plaatide laenutus</td>
            <td class="column4 style3 s">Ei</td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row44">
            <td class="column0">&nbsp;</td>
            <td class="column1">&nbsp;</td>
            <td class="column2">&nbsp;</td>
            <td class="column3">&nbsp;</td>
            <td class="column4 style6 null"></td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row45">
            <td class="column0">&nbsp;</td>
            <td class="column1">&nbsp;</td>
            <td class="column2">&nbsp;</td>
            <td class="column3">&nbsp;</td>
            <td class="column4 style6 null"></td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>
          <tr class="row46">
            <td class="column0">&nbsp;</td>
            <td class="column1">&nbsp;</td>
            <td class="column2">&nbsp;</td>
            <td class="column3">&nbsp;</td>
            <td class="column4 style6 null"></td>
            <td class="column5">&nbsp;</td>
            <td class="column6">&nbsp;</td>
            <td class="column7">&nbsp;</td>
            <td class="column8">&nbsp;</td>
            <td class="column9">&nbsp;</td>
            <td class="column10">&nbsp;</td>
            <td class="column11">&nbsp;</td>
            <td class="column12">&nbsp;</td>
            <td class="column13">&nbsp;</td>
            <td class="column14">&nbsp;</td>
            <td class="column15">&nbsp;</td>
            <td class="column16">&nbsp;</td>
            <td class="column17">&nbsp;</td>
            <td class="column18">&nbsp;</td>
            <td class="column19">&nbsp;</td>
            <td class="column20">&nbsp;</td>
            <td class="column21">&nbsp;</td>
            <td class="column22">&nbsp;</td>
            <td class="column23">&nbsp;</td>
            <td class="column24">&nbsp;</td>
            <td class="column25">&nbsp;</td>
            <td class="column26">&nbsp;</td>
            <td class="column27">&nbsp;</td>
            <td class="column28">&nbsp;</td>
          </tr>`
    }
  ];

}
